---
title: "TADPOLE_BESS"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE and BESS
BESS Analysis

## Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```

## Loading BSWiMS Results

```{r}
opo <- par(no.readonly = TRUE)

load("~/GitHub/BSWiMS/TADPOLE_BSWIMS_Results.RData")
op <- opo
```



# Predicting ADAS13

Here we will diagnose ADAS13


## Learning ADAS13

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
BESSml <- BESS(ADAS13~.,TADPOLECrossMRITrain)

prreg <- predictionStats_regression(cbind(TADPOLECrossMRITest$ADAS13,predict(BESSml,TADPOLECrossMRITest)),"ADAS13")
pander::pander(prreg)
par(op)

```


## Decorrelated

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
BESSmlD <- BESS(ADAS13~.,TADPOLECrossMRITrainD)

prreg <- predictionStats_regression(cbind(TADPOLECrossMRITestD$ADAS13,predict(BESSmlD,TADPOLECrossMRITestD)),"ADAS13")
pander::pander(prreg)
par(op)

```



# Diagnosis MCI vs AD

## Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_TRAIN$DX <- as.factor(TADPOLE_DX_TRAIN$DX)

BESSDXml <- BESS(DX~.,TADPOLE_DX_TRAIN)
pr <- predict(BESSDXml,TADPOLE_DX_TEST,type="response")

prBin <- predictionStats_binary(cbind(TADPOLE_DX_TEST$DX,pr),"MCI vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)

```



### Decorrelated ML

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_TRAIND$DX <- as.factor(TADPOLE_DX_TRAIND$DX)

BESSDXmlD <- BESS(DX~.,TADPOLE_DX_TRAIND)


prBin <- predictionStats_binary(cbind(TADPOLE_DX_TESTD$DX,predict(BESSDXmlD,TADPOLE_DX_TESTD,type="response")),"MCI vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)

```



# Diagnosis NL vs AD

## Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_NLDE_TRAIN$DX <- as.factor(TADPOLE_DX_NLDE_TRAIN$DX)
BESSDXmlNLDE <- BESS(DX~.,TADPOLE_DX_NLDE_TRAIN)

prBin <- predictionStats_binary(cbind(TADPOLE_DX_NLDE_TEST$DX,predict(BESSDXmlNLDE,TADPOLE_DX_NLDE_TEST)[,2]),"NL vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)

```


## Decorrelated Set

### Learning 

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_NLDE_TRAIND$DX <- as.factor(TADPOLE_DX_NLDE_TRAIND$DX)

BESSDXmlNLDED <- BESS(DX~.,TADPOLE_DX_NLDE_TRAIND)

prBin <- predictionStats_binary(cbind(TADPOLE_DX_NLDE_TESTD$DX,predict(BESSDXmlNLDED,TADPOLE_DX_NLDE_TESTD)[,2]),"NL vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)

```


# Prognosis MCI to AD Conversion


## Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}


bConvml <- BESS(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIN)

ptestr <- predict(bConvml,TADPOLE_Conv_TEST)
ptestl <- log(ptestr)
boxplot(ptestl~TADPOLE_Conv_TEST$status)
boxplot(ptestr~TADPOLE_Conv_TEST$status)



perdsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)

if (max(ptestl)>0 && min(ptestl)<0 )
{
  prSurv <- predictionStats_survival(perdsurv,"MCI to  AD Conversion")
  pander::pander(prSurv$CIRisk)
  pander::pander(prSurv$CILp)
  pander::pander(prSurv$spearmanCI)
}

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)

```


## Decorrelated


### Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}


bConvmlD <- BESS(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIND)

ptestr <- predict(bConvmlD,TADPOLE_Conv_TESTD)
ptestl <- log(ptestr)
boxplot(ptestl~TADPOLE_Conv_TEST$status)
boxplot(ptestr~TADPOLE_Conv_TEST$status)

perdsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)


if (max(ptestl)>0 && min(ptestl)<0 )
{
  prSurv <- predictionStats_survival(perdsurv,"MCI to  AD Conversion")
  pander::pander(prSurv$CIRisk)
  pander::pander(prSurv$CILp)
  pander::pander(prSurv$spearmanCI)
}

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TESTD$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)

```

### The End

.


