---
title: "TADPOLE_RPART"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE and RPART

RPART Analysis

## Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```

## Loading BSWiMS Results

```{r}
opo <- par(no.readonly = TRUE)

load("~/GitHub/BSWiMS/TADPOLE_BSWIMS_Results.RData")
op <- opo
```

# Predicting ADAS13

Here we will diagnose ADAS13

## Learning ADAS13

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
RPARTml <- rpart::rpart(ADAS13~.,TADPOLECrossMRITrain)
pander::pander(as.matrix(RPARTml$variable.importance))

prreg <- predictionStats_regression(cbind(TADPOLECrossMRITest$ADAS13,predict(RPARTml,TADPOLECrossMRITest)),"ADAS13")
pander::pander(prreg)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTml,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTml,use.n = TRUE,all=TRUE,cex=0.5)
par(op)

```

## Decorrelated

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
RPARTmlD <- rpart::rpart(ADAS13~.,TADPOLECrossMRITrainD)
pander::pander(as.matrix(RPARTmlD$variable.importance))

prreg <- predictionStats_regression(cbind(TADPOLECrossMRITestD$ADAS13,predict(RPARTmlD,TADPOLECrossMRITestD)),"ADAS13")
pander::pander(prreg)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTmlD,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTmlD,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

# Diagnosis MCI vs AD

## Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_TRAIN$DX <- as.factor(TADPOLE_DX_TRAIN$DX)

RPARTDXml <- rpart::rpart(DX~.,TADPOLE_DX_TRAIN)
#RPARTDXml <- rpart::rpart(DX~.,TADPOLE_DX_TRAIN,
#                          control = rpart::rpart.control(xval = 10, minbucket = 2, cp = 0.01))
#RPARTDXml <- rpart::prune(RPARTDXml, cp = 0.02)

pander::pander(as.matrix(RPARTDXml$variable.importance))

prBin <- predictionStats_binary(cbind(TADPOLE_DX_TEST$DX,predict(RPARTDXml,TADPOLE_DX_TEST)[,2]),"MCI vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTDXml,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTDXml,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

### Decorrelated ML

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_TRAIND$DX <- as.factor(TADPOLE_DX_TRAIND$DX)

RPARTDXmlD <- rpart::rpart(DX~.,TADPOLE_DX_TRAIND)
pander::pander(as.matrix(RPARTDXmlD$variable.importance))


prBin <- predictionStats_binary(cbind(TADPOLE_DX_TESTD$DX,predict(RPARTDXmlD,TADPOLE_DX_TESTD)[,2]),"MCI vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTDXmlD,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTDXmlD,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

# Diagnosis NL vs AD

## Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_NLDE_TRAIN$DX <- as.factor(TADPOLE_DX_NLDE_TRAIN$DX)

RPARTDXmlNLDE <- rpart::rpart(DX~.,TADPOLE_DX_NLDE_TRAIN)
pander::pander(as.matrix(RPARTDXmlNLDE$variable.importance))

#RPARTDXmlNLDE <- rpart::rpart(DX~.,TADPOLE_DX_NLDE_TRAIN,
#                          control = rpart::rpart.control(xval = 10, minbucket = 2, cp = 0.0))
#RPARTDXmlNLDE <- rpart::prune(RPARTDXmlNLDE, cp = 0.02)

prBin <- predictionStats_binary(cbind(TADPOLE_DX_NLDE_TEST$DX,predict(RPARTDXmlNLDE,TADPOLE_DX_NLDE_TEST)[,2]),"NL vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTDXmlNLDE,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTDXmlNLDE,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

## Decorrelated Set

### Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
TADPOLE_DX_NLDE_TRAIND$DX <- as.factor(TADPOLE_DX_NLDE_TRAIND$DX)

RPARTDXmlNLDED <- rpart::rpart(DX~.,TADPOLE_DX_NLDE_TRAIND)
pander::pander(as.matrix(RPARTDXmlNLDED$variable.importance))

#                          control = rpart::rpart.control(xval = 10, minbucket = 2, cp = 0.01))
#RPARTDXmlNLDED <- rpart::prune(RPARTDXmlNLDED, cp = 0.02)

prBin <- predictionStats_binary(cbind(TADPOLE_DX_NLDE_TESTD$DX,predict(RPARTDXmlNLDED,TADPOLE_DX_NLDE_TESTD)[,2]),"NL vs Dementia")
pander::pander(prBin$aucs)
pander::pander(prBin$accc)
pander::pander(prBin$berror)
pander::pander(prBin$sensitivity)
par(op)
par(mar = rep(0.2, 4))
plot(RPARTDXmlNLDED,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(RPARTDXmlNLDED,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

# Prognosis MCI to AD Conversion

## Learning Survival

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

bConvml <- rpart::rpart(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIN)
pander::pander(as.matrix(bConvml$variable.importance))

ptestr <- predict(bConvml,TADPOLE_Conv_TEST)
ptestl <- log(ptestr)
boxplot(ptestl~TADPOLE_Conv_TEST$status)
boxplot(ptestr~TADPOLE_Conv_TEST$status)

par(op)
par(mar = rep(0.2, 4))
plot(bConvml,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(bConvml,use.n = TRUE,all=TRUE,cex=0.75)
par(op)


```

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

perdsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)

if (max(ptestl)>0 && min(ptestl)<0 )
{
  prSurv <- predictionStats_survival(perdsurv,"MCI to  AD Conversion")
  pander::pander(prSurv$CIRisk)
  pander::pander(prSurv$CILp)
  pander::pander(prSurv$spearmanCI)
}

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"MCI to  AD Conversion")


par(op)

```


```{r results = "asis"}
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

```

The decorrelation

## Decorrelated

### Learning

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}


bConvmlD <- rpart::rpart(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIND)
pander::pander(as.matrix(bConvmlD$variable.importance))

ptestr <- predict(bConvmlD,TADPOLE_Conv_TESTD)
ptestl <- log(ptestr)
boxplot(ptestl~TADPOLE_Conv_TEST$status)
boxplot(ptestr~TADPOLE_Conv_TEST$status)

perdsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)


if (max(ptestl)>0 && min(ptestl)<0 )
{
  prSurv <- predictionStats_survival(perdsurv,"MCI to  AD Conversion")
  pander::pander(prSurv$CIRisk)
  pander::pander(prSurv$CILp)
  pander::pander(prSurv$spearmanCI)
}

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TESTD$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)
par(mar = rep(0.2, 4))
plot(bConvmlD,branch = 0.2,uniform = TRUE, compress = TRUE,margin = 0.1)
text(bConvmlD,use.n = TRUE,all=TRUE,cex=0.75)
par(op)

```

### The End

.
